"""agent_factory — the imperative logic for building a new Hermes agent.

Pure functions (no web framework). Exposed to the Builder Hermes agent as an
MCP tool (net_mcp/builder_tools.py) so the Builder autonomously decides to
build, and used by nothing else. Every agent it creates is itself a Hermes
autonomous agent (own profile + agent_bridge MCP + a thin forwarder service).
"""
from __future__ import annotations

import json
import logging
import os
import re
import secrets
import subprocess
from pathlib import Path

from net_agents import registry_io

HERE = Path(__file__).resolve().parent          # net_agents/
ROOT = HERE.parent                               # telegram_voice/
_ENV = ROOT / ".env"
if _ENV.exists():
    for _line in _ENV.read_text(encoding="utf-8").splitlines():
        if "=" in _line and not _line.strip().startswith("#"):
            _k, _, _v = _line.partition("=")
            os.environ.setdefault(_k.strip(), _v.strip())

OPENAI_KEY = os.getenv("OPENAI_API_KEY", "")
HERMES = str(Path.home() / ".local" / "bin" / "hermes")
HVENV = str(Path.home() / ".hermes" / "hermes-agent" / "venv" / "bin" / "python")
PROFILES = Path.home() / ".hermes" / "profiles"
PROXY_URL = os.getenv("TERRA_PROXY_URL", "http://127.0.0.1:8650/v1")
AGENTS_JSON = ROOT / "agents.json"
STATE = ROOT / "state"
VENV_PY = str(ROOT / ".venv" / "bin" / "python")

log = logging.getLogger("agent_factory")

NETWORK_DIRECTIVE = """

## Working in the network (answer what you know, route what you can't)
You are a strong model — use your own knowledge freely. ANSWER DIRECTLY anything you can answer with full confidence and WITHOUT needing a tool or live data: general knowledge, translation, reasoning, writing, math, explanations. Do not route things you genuinely know.

Delegate ONLY when one of these is true:
- You are not fully confident your answer is correct — never bluff; a confident wrong answer is the worst outcome.
- It needs LIVE or EXTERNAL data you don't have (current facts, prices, weather, a web page, or the user's own schedule / memory / files).
- It needs an ACTION or tool you don't have (operate a website/app, save a memory, build something, etc.).
- It is squarely another agent's specialised job.

To delegate: use ask_agent to send it to the right agent (list_agents shows what each one does), or ask the 'router' agent when you're unsure who. Relay their answer. If nobody can help, say plainly that you don't know.
"""

HERMES_CONFIG = """# {name}brain — Hermes brain for the {name} agent (gpt-5.6-terra via terra proxy)
model:
  default: "gpt-5.6-terra"
  provider: "openai-direct"
  context_length: 128000
  max_tokens: 4096
providers:
  openai-direct:
    base_url: "{proxy}"
    key_env: "OPENAI_API_KEY"
    api_mode: "chat_completions"
agent:
  max_turns: 20
platform_toolsets:
  api_server: [todo]
mcp_servers:
  memory_layer:
    command: "{hvenv}"
    args: ["-m", "net_mcp.memory_layer"]
    env:
      SELF_AGENT: "{name}"
      PYTHONPATH: "{tv}"
  agent_bridge:
    command: "{hvenv}"
    args: ["-m", "net_mcp.agent_bridge"]
    env:
      HERMES_HUB: "http://127.0.0.1:8484"
      SELF_AGENT: "{name}"
      PYTHONPATH: "{tv}"
"""

AGENT_TEMPLATE = '''"""{title} agent — a Hermes autonomous agent generated by the Builder.
Its Hermes runtime ({name}brain, :{brain_port}) handles requests autonomously
with its persona + the agent_bridge MCP tools (so it can message any peer)."""
from net_agents.hermes_service import make_agent_app
app = make_agent_app("{name}", brain_port={brain_port}, brain_key={brain_key!r})
'''


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", name.lower())[:24] or "agent"


def _registry() -> dict:
    return registry_io.read_lenient()


def build_agent(name: str, purpose: str, persona: str) -> dict:
    """Create + launch a new Hermes autonomous agent. Returns a status dict."""
    slug = _slug(name)

    # Reserve the slug + both ports and write the registry entry in ONE locked,
    # atomic step BEFORE launching anything — this closes the double-allocation
    # TOCTOU and the silent last-writer-wins registry drop under concurrent builds.
    def _reserve(reg: dict) -> dict:
        if slug in reg:
            return {"ok": False, "error": f"agent '{slug}' already exists"}
        bp = registry_io.allocate_port(reg, registry_io.BRAIN_RANGE, set())
        ap = registry_io.allocate_port(reg, registry_io.AGENT_RANGE, {bp})
        reg[slug] = {"type": "http", "url": f"http://localhost:{ap}/ask",
                     "description": purpose, "brain_port": bp,
                     "agent_port": ap, "generated": True}
        return {"ok": True, "brain_port": bp, "agent_port": ap}

    try:
        reserved = registry_io.with_registry(_reserve)
    except registry_io.RegistryUnreadable as e:
        return {"ok": False, "error": f"registry unreadable, refusing to build: {e}"}
    if not reserved.get("ok"):
        return reserved
    brain_port = reserved["brain_port"]
    agent_port = reserved["agent_port"]
    brain_key = f"{slug}brain-{secrets.token_hex(10)}"  # >=16 chars (Hermes min)

    # 1) Hermes profile (the agent's brain), with agent_bridge MCP for peer calls
    subprocess.run([HERMES, "profile", "create", f"{slug}brain",
                    "--description", f"Hermes brain for the {slug} agent"],
                   capture_output=True, text=True, timeout=90)
    pdir = PROFILES / f"{slug}brain"
    (pdir / ".env").write_text(
        f"OPENAI_API_KEY={OPENAI_KEY}\nAPI_SERVER_ENABLED=true\n"
        f"API_SERVER_KEY={brain_key}\nAPI_SERVER_PORT={brain_port}\n")
    os.chmod(pdir / ".env", 0o600)
    (pdir / "config.yaml").write_text(HERMES_CONFIG.format(
        name=slug, proxy=PROXY_URL, hvenv=HVENV, tv=str(ROOT)))
    persona = persona.rstrip() + NETWORK_DIRECTIVE
    (pdir / "SOUL.md").write_text(persona)

    # 2) the thin forwarder service
    (HERE / f"{slug}.py").write_text(AGENT_TEMPLATE.format(
        title=name, name=slug, brain_port=brain_port, brain_key=brain_key))

    # 2b) persona doc so its graph node is clickable
    ctx = HERE / "context"; ctx.mkdir(exist_ok=True)
    (ctx / f"{slug}.md").write_text(
        f"# {name} agent — generated\n\n{purpose}\n\n## Persona\n\n{persona}\n\n"
        f"A Hermes autonomous agent ({slug}brain, gpt-5.6-terra). Talks to peers "
        f"via list_agents / ask_agent.\n")

    # 3) snapshot the composed system prompt so the Audit agent can detect drift
    try:
        from net_agents import prompt_snapshot
        prompt_snapshot.snapshot(slug, persona)
    except Exception:
        pass

    # 4) launch brain + forwarder (brain_env strips the Telegram token so the new
    #    gateway runs api_server only and won't fight the bot for it)
    from net_agents.lifecycle import brain_env
    subprocess.Popen([HERMES, "-p", f"{slug}brain", "gateway", "run", "--replace"],
                     stdout=open(STATE / f"hermes-{slug}brain.log", "a"),
                     stderr=subprocess.STDOUT, cwd=str(ROOT), env=brain_env())
    subprocess.Popen([VENV_PY, "-m", "uvicorn", f"net_agents.{slug}:app",
                      "--port", str(agent_port)],
                     stdout=open(STATE / f"{slug}.log", "a"),
                     stderr=subprocess.STDOUT, cwd=str(ROOT))
    log.info("built agent '%s' (service :%d, brain :%d)", slug, agent_port, brain_port)
    return {"ok": True, "name": slug, "agent_port": agent_port,
            "brain_port": brain_port}
