"""agent_factory — the imperative logic for building a new Hermes agent.

Pure functions (no web framework). Exposed to the Builder Hermes agent as an
MCP tool (net_mcp/builder_tools.py) so the Builder autonomously decides to
build, and used by nothing else. Every agent it creates is itself a Hermes
autonomous agent (own profile + agent_bridge MCP + a thin forwarder service).
"""
from __future__ import annotations

import json
import logging
import os
import re
import secrets
import socket
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent          # net_agents/
ROOT = HERE.parent                               # telegram_voice/
for _line in (ROOT / ".env").read_text(encoding="utf-8").splitlines():
    if "=" in _line and not _line.strip().startswith("#"):
        _k, _, _v = _line.partition("=")
        os.environ.setdefault(_k.strip(), _v.strip())

OPENAI_KEY = os.getenv("OPENAI_API_KEY", "")
HERMES = str(Path.home() / ".local" / "bin" / "hermes")
HVENV = str(Path.home() / ".hermes" / "hermes-agent" / "venv" / "bin" / "python")
PROFILES = Path.home() / ".hermes" / "profiles"
PROXY_URL = os.getenv("TERRA_PROXY_URL", "http://127.0.0.1:8650/v1")
AGENTS_JSON = ROOT / "agents.json"
STATE = ROOT / "state"
VENV_PY = str(ROOT / ".venv" / "bin" / "python")

log = logging.getLogger("agent_factory")

HERMES_CONFIG = """# {name}brain — Hermes brain for the {name} agent (gpt-5.6-terra via terra proxy)
model:
  default: "gpt-5.6-terra"
  provider: "openai-direct"
  context_length: 128000
  max_tokens: 4096
providers:
  openai-direct:
    base_url: "{proxy}"
    key_env: "OPENAI_API_KEY"
    api_mode: "chat_completions"
agent:
  max_turns: 20
platform_toolsets:
  api_server: [todo]
mcp_servers:
  agent_bridge:
    command: "{hvenv}"
    args: ["-m", "net_mcp.agent_bridge"]
    env:
      HERMES_HUB: "http://127.0.0.1:8484"
      SELF_AGENT: "{name}"
      PYTHONPATH: "{tv}"
"""

AGENT_TEMPLATE = '''"""{title} agent — a Hermes autonomous agent generated by the Builder.
Its Hermes runtime ({name}brain, :{brain_port}) handles requests autonomously
with its persona + the agent_bridge MCP tools (so it can message any peer)."""
from net_agents.hermes_service import make_agent_app
app = make_agent_app("{name}", brain_port={brain_port}, brain_key={brain_key!r})
'''


def _free_port(lo: int, hi: int) -> int:
    for p in range(lo, hi):
        with socket.socket() as s:
            if s.connect_ex(("127.0.0.1", p)) != 0:
                return p
    raise RuntimeError(f"no free port in {lo}-{hi}")


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", name.lower())[:24] or "agent"


def _registry() -> dict:
    try:
        return json.loads(AGENTS_JSON.read_text())
    except Exception:
        return {}


def build_agent(name: str, purpose: str, persona: str) -> dict:
    """Create + launch a new Hermes autonomous agent. Returns a status dict."""
    slug = _slug(name)
    reg = _registry()
    if slug in reg:
        return {"ok": False, "error": f"agent '{slug}' already exists"}

    brain_port = _free_port(8660, 8699)
    agent_port = _free_port(9110, 9199)
    brain_key = f"{slug}brain-{secrets.token_hex(10)}"  # >=16 chars (Hermes min)

    # 1) Hermes profile (the agent's brain), with agent_bridge MCP for peer calls
    subprocess.run([HERMES, "profile", "create", f"{slug}brain",
                    "--description", f"Hermes brain for the {slug} agent"],
                   capture_output=True, text=True, timeout=90)
    pdir = PROFILES / f"{slug}brain"
    (pdir / ".env").write_text(
        f"OPENAI_API_KEY={OPENAI_KEY}\nAPI_SERVER_ENABLED=true\n"
        f"API_SERVER_KEY={brain_key}\nAPI_SERVER_PORT={brain_port}\n")
    os.chmod(pdir / ".env", 0o600)
    (pdir / "config.yaml").write_text(HERMES_CONFIG.format(
        name=slug, proxy=PROXY_URL, hvenv=HVENV, tv=str(ROOT)))
    (pdir / "SOUL.md").write_text(persona)

    # 2) the thin forwarder service
    (HERE / f"{slug}.py").write_text(AGENT_TEMPLATE.format(
        title=name, name=slug, brain_port=brain_port, brain_key=brain_key))

    # 2b) persona doc so its graph node is clickable
    ctx = HERE / "context"; ctx.mkdir(exist_ok=True)
    (ctx / f"{slug}.md").write_text(
        f"# {name} agent — generated\n\n{purpose}\n\n## Persona\n\n{persona}\n\n"
        f"A Hermes autonomous agent ({slug}brain, gpt-5.6-terra). Talks to peers "
        f"via list_agents / ask_agent.\n")

    # 3) registry entry — instantly reachable by every other agent
    reg[slug] = {"type": "http", "url": f"http://localhost:{agent_port}/ask",
                 "description": purpose, "brain_port": brain_port,
                 "agent_port": agent_port, "generated": True}
    AGENTS_JSON.write_text(json.dumps(reg, indent=2, ensure_ascii=False))

    # 4) launch brain + forwarder
    subprocess.Popen([HERMES, "-p", f"{slug}brain", "gateway", "run", "--force"],
                     stdout=open(STATE / f"hermes-{slug}brain.log", "a"),
                     stderr=subprocess.STDOUT, cwd=str(ROOT))
    subprocess.Popen([VENV_PY, "-m", "uvicorn", f"net_agents.{slug}:app",
                      "--port", str(agent_port)],
                     stdout=open(STATE / f"{slug}.log", "a"),
                     stderr=subprocess.STDOUT, cwd=str(ROOT))
    log.info("built agent '%s' (service :%d, brain :%d)", slug, agent_port, brain_port)
    return {"ok": True, "name": slug, "agent_port": agent_port,
            "brain_port": brain_port}
