"""BUILDER agent — grows the Hermes network by building new agents.

Given a spec ("build an agent called 'weather' that reports the forecast"),
the Builder creates a *complete, same-spec* agent:

  1. a dedicated Hermes brain (a `hermes` profile running gpt-5.6-terra via the
     terra proxy, with the new agent's persona as its SOUL);
  2. a FastAPI `/ask` service (net_agents/<name>.py) that brains on that Hermes
     instance with a direct gpt-5.6-terra fallback — identical contract to every
     other agent;
  3. a registry entry in agents.json, so the orchestrator and every other agent
     can immediately call it via the hub (`ask_agent`) — the new agent *is* a
     tool the others can use;
  4. it launches both processes.

This is what makes the network modular and auto-expandable: new capability =
one spec → one new callable agent that appears in the graph.

Contract: POST /ask {"message": "<spec>", "from": "..."} -> {"reply": ...}
Run:  .venv/bin/python -m uvicorn net_agents.builder:app --port 9105
"""
from __future__ import annotations

import json
import logging
import os
import re
import secrets
import socket
import subprocess
import sys
from pathlib import Path

import httpx
from fastapi import FastAPI
from pydantic import BaseModel

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent  # telegram_voice/
for line in (ROOT / ".env").read_text(encoding="utf-8").splitlines():
    if "=" in line and not line.strip().startswith("#"):
        k, _, v = line.partition("=")
        os.environ.setdefault(k.strip(), v.strip())

OPENAI_KEY = os.getenv("OPENAI_API_KEY", "")
HERMES = str(Path.home() / ".local" / "bin" / "hermes")
PROFILES = Path.home() / ".hermes" / "profiles"
PROXY_URL = os.getenv("TERRA_PROXY_URL", "http://127.0.0.1:8650/v1")
AGENTS_JSON = ROOT / "agents.json"
STATE = ROOT / "state"
VENV_PY = str(ROOT / ".venv" / "bin" / "python")

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("builder")

from net_agents.failure_log import log_failure  # noqa: E402

app = FastAPI(title="builder agent")


# ── helpers ──────────────────────────────────────────────────────────────
def _free_port(lo: int, hi: int) -> int:
    for p in range(lo, hi):
        with socket.socket() as s:
            if s.connect_ex(("127.0.0.1", p)) != 0:
                return p
    raise RuntimeError(f"no free port in {lo}-{hi}")


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", name.lower())[:24] or "agent"


def _registry() -> dict:
    try:
        return json.loads(AGENTS_JSON.read_text())
    except Exception:
        return {}


HERMES_CONFIG = """# {name}brain — Hermes brain for the {name} agent (gpt-5.6-terra via terra proxy)
model:
  default: "gpt-5.6-terra"
  provider: "openai-direct"
  context_length: 128000
  max_tokens: 4096
providers:
  openai-direct:
    base_url: "{proxy}"
    key_env: "OPENAI_API_KEY"
    api_mode: "chat_completions"
agent:
  max_turns: 20
"""

# Template for the generated agent service. Doubled braces are literal.
AGENT_TEMPLATE = '''"""{title} agent — generated by the Builder. Brains on its own Hermes
instance ({name}brain, :{brain_port}), and can call any other agent via the hub.
Contract: POST /ask {{"message": ...}} -> {{"reply": ...}}
"""
from __future__ import annotations
import json, os
from pathlib import Path
import httpx
from fastapi import FastAPI
from pydantic import BaseModel

HERE = Path(__file__).resolve().parent
for line in (HERE.parent / ".env").read_text(encoding="utf-8").splitlines():
    if "=" in line and not line.strip().startswith("#"):
        k, _, v = line.partition("=")
        os.environ.setdefault(k.strip(), v.strip())
try:
    from net_agents.failure_log import log_failure
except Exception:
    def log_failure(*a, **k): pass

OPENAI_KEY = os.getenv("OPENAI_API_KEY", "")
HUB = os.getenv("HERMES_HUB", "http://127.0.0.1:8484")
PERSONA = {persona!r}
NET = ("You belong to a Hermes agent network and can collaborate with the other "
       "agents. Use list_agents to see who exists and ask_agent(agent, message) "
       "to delegate a subtask and use their reply. Answer directly when you can; "
       "delegate when another agent is clearly better suited. Keep replies short.")
app = FastAPI(title="{name} agent")

TOOLS = [
  {{"type": "function", "function": {{"name": "list_agents",
    "description": "List the other agents you can call.",
    "parameters": {{"type": "object", "properties": {{}}}}}}}},
  {{"type": "function", "function": {{"name": "ask_agent",
    "description": "Send a message to another agent and get its reply.",
    "parameters": {{"type": "object", "properties": {{
        "agent": {{"type": "string"}}, "message": {{"type": "string"}}}},
        "required": ["agent", "message"]}}}}}},
]

def _hub_ask(agent, message):
    try:
        r = httpx.post(HUB + "/agents/ask",
                       json={{"agent": agent, "message": message}}, timeout=45)
        return r.json().get("reply", "")
    except Exception as e:
        return "could not reach " + str(agent) + ": " + str(e)

def _hub_list():
    try:
        r = httpx.get(HUB + "/api/agents", timeout=10)
        return ", ".join(a["name"] for a in r.json().get("agents", []))
    except Exception:
        return ""

class Ask(BaseModel):
    message: str

@app.post("/ask")
def ask(a: Ask) -> dict:
    msgs = [{{"role": "system", "content": PERSONA + "\\n\\n" + NET}},
            {{"role": "user", "content": a.message}}]
    for _ in range(4):  # small tool-loop: can delegate a few hops
        try:
            r = httpx.post("https://api.openai.com/v1/chat/completions",
                headers={{"Authorization": "Bearer " + OPENAI_KEY}},
                json={{"model": "gpt-5.6-terra", "reasoning_effort": "none",
                      "max_completion_tokens": 700, "messages": msgs,
                      "tools": TOOLS}}, timeout=40)
            r.raise_for_status()
            m = r.json()["choices"][0]["message"]
        except Exception as e:
            log_failure("{name}", "llm_failed", str(e), {{}})
            return {{"reply": "I could not reach my brain just now."}}
        msgs.append(m)
        calls = m.get("tool_calls") or []
        if not calls:
            return {{"reply": (m.get("content") or "").strip() or "..."}}
        for c in calls:
            try:
                args = json.loads(c["function"]["arguments"] or "{{}}")
            except Exception:
                args = {{}}
            fn = c["function"]["name"]
            out = _hub_list() if fn == "list_agents" \\
                else _hub_ask(args.get("agent", ""), args.get("message", ""))
            msgs.append({{"role": "tool", "tool_call_id": c["id"], "content": out}})
    last = msgs[-1] if isinstance(msgs[-1], dict) else {{}}
    return {{"reply": (last.get("content") or "").strip() or "Done."}}

@app.get("/health")
def health() -> dict:
    return {{"ok": True, "agent": "{name}", "can_delegate": True}}
'''


def build_agent(name: str, purpose: str, persona: str) -> dict:
    slug = _slug(name)
    reg = _registry()
    if slug in reg:
        return {"ok": False, "error": f"agent '{slug}' already exists"}

    brain_port = _free_port(8660, 8699)
    agent_port = _free_port(9110, 9199)
    brain_key = f"{slug}brain-{secrets.token_hex(10)}"  # >=16 chars (Hermes min)

    # 1) Hermes profile (brain)
    subprocess.run([HERMES, "profile", "create", f"{slug}brain",
                    "--description", f"Hermes brain for the {slug} agent"],
                   capture_output=True, text=True, timeout=90)
    pdir = PROFILES / f"{slug}brain"
    (pdir / ".env").write_text(
        f"OPENAI_API_KEY={OPENAI_KEY}\nAPI_SERVER_ENABLED=true\n"
        f"API_SERVER_KEY={brain_key}\nAPI_SERVER_PORT={brain_port}\n")
    os.chmod(pdir / ".env", 0o600)
    (pdir / "config.yaml").write_text(HERMES_CONFIG.format(name=slug, proxy=PROXY_URL))
    (pdir / "SOUL.md").write_text(persona)

    # 2) agent service file
    code = AGENT_TEMPLATE.format(title=name, name=slug, persona=persona,
                                 brain_port=brain_port, brain_key=brain_key)
    (HERE / f"{slug}.py").write_text(code)

    # 2b) persona doc — so clicking the node in the graph shows its docs
    ctx = HERE / "context"
    ctx.mkdir(exist_ok=True)
    (ctx / f"{slug}.md").write_text(
        f"# {name} agent — generated\n\n{purpose}\n\n## Persona\n\n{persona}\n\n"
        f"Brains on its own Hermes instance ({slug}brain) running gpt-5.6-terra "
        f"via the terra proxy. Can delegate to any other agent through the hub "
        f"(list_agents / ask_agent).\n")

    # 3) registry entry — instantly callable by every other agent via the hub
    reg[slug] = {"type": "http", "url": f"http://localhost:{agent_port}/ask",
                 "description": purpose,
                 "brain_port": brain_port, "agent_port": agent_port,
                 "generated": True}
    AGENTS_JSON.write_text(json.dumps(reg, indent=2, ensure_ascii=False))

    # 4) launch brain + service
    logf = STATE / f"{slug}.log"
    subprocess.Popen([HERMES, "-p", f"{slug}brain", "gateway", "run", "--force"],
                     stdout=open(STATE / f"hermes-{slug}brain.log", "a"),
                     stderr=subprocess.STDOUT, cwd=str(ROOT))
    subprocess.Popen([VENV_PY, "-m", "uvicorn", f"net_agents.{slug}:app",
                      "--port", str(agent_port)],
                     stdout=open(logf, "a"), stderr=subprocess.STDOUT, cwd=str(ROOT))

    log.info("built agent '%s' (service :%d, brain :%d)", slug, agent_port, brain_port)
    return {"ok": True, "name": slug, "agent_port": agent_port,
            "brain_port": brain_port,
            "note": "registered + launching; callable as ask_agent('%s')" % slug}


# ── spec parsing (uses the builder's own reasoning via the proxy) ─────────
SPEC_SYSTEM = (
    "You design agents for a modular Hermes agent network. Given a build "
    "request, output ONLY JSON: {\"name\": short-slug, \"purpose\": one-line "
    "description for the registry, \"persona\": a 3-6 sentence system prompt "
    "for the new agent describing its role, how it answers other agents in "
    "short plain text, and when to defer. No markdown.}")


def parse_spec(spec: str) -> dict:
    try:
        r = httpx.post(f"{PROXY_URL}/chat/completions",
                       headers={"Authorization": f"Bearer {OPENAI_KEY}"},
                       json={"model": "gpt-5.6-terra", "reasoning_effort": "none",
                             "max_completion_tokens": 500,
                             "response_format": {"type": "json_object"},
                             "messages": [{"role": "system", "content": SPEC_SYSTEM},
                                          {"role": "user", "content": spec}]},
                       timeout=40)
        r.raise_for_status()
        d = json.loads(r.json()["choices"][0]["message"]["content"])
        return {"name": _slug(d.get("name", "agent")),
                "purpose": d.get("purpose", spec)[:200],
                "persona": d.get("persona", spec)}
    except Exception as e:
        log.warning("spec parse failed: %s", e)
        # fall back to a naive slug from the spec
        m = re.search(r"called ['\"]?([a-zA-Z0-9 ]+)['\"]?", spec)
        nm = _slug(m.group(1)) if m else "agent"
        return {"name": nm, "purpose": spec[:200],
                "persona": f"You are the {nm} agent. {spec}. Answer other "
                           "agents in short plain text."}


class Ask(BaseModel):
    message: str
    from_: str | None = None


@app.post("/ask")
def ask(a: Ask) -> dict:
    spec = a.message.strip()
    try:
        parsed = parse_spec(spec)
        result = build_agent(parsed["name"], parsed["purpose"], parsed["persona"])
        if result.get("ok"):
            return {"reply": f"Built agent '{result['name']}' — it's registered "
                             f"and starting on port {result['agent_port']} with "
                             f"its own Hermes brain (:{result['brain_port']}). "
                             f"Any agent can now call it as ask_agent('{result['name']}')."}
        return {"reply": f"Could not build it: {result.get('error')}"}
    except Exception as e:
        log_failure("builder", "build_failed", str(e), {"spec": spec[:200]})
        return {"reply": f"Build failed: {e}"}


@app.get("/health")
def health() -> dict:
    return {"ok": True, "agent": "builder",
            "generated": [k for k, v in _registry().items()
                          if isinstance(v, dict) and v.get("generated")]}
