"""planner agent — a Hermes autonomous agent generated by the Builder.
Its Hermes runtime (plannerbrain, :8660) handles requests autonomously
with its persona + the agent_bridge MCP tools (so it can message any peer)."""
from net_agents.hermes_service import make_agent_app
app = make_agent_app("planner", brain_port=8660, brain_key="plannerbrain-local")
